language: generic
dist: trusty
sudo: required
services:
- docker
env: 
script:
- ./travis-build.sh
before_install:
- openssl aes-256-cbc -K $encrypted_0afed5a974a1_key -iv $encrypted_0afed5a974a1_iv
  -in test-pubsub.json.enc -out test-pubsub.json -d
