version: '2'
services:
  web:
    build: .
    command: ""
    depends_on: 
     - db
    ports:
     - "4444:8080"

  db:
    image: mongo
    environment:
     - MONGODB_DBNAME= mydb
    volumes: 
     - './data:/data/db'
